version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=task
      - DB_USER=app_user
      - DB_PASSWORD=strongpassword
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=task
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=strongpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --default-authentication-plugin=mysql_native_password  --host_cache_size=0  --pid-file=/var/lib/mysql/mysqld.pid
    ports:
      - "3307:3306"

volumes:
  db_data:
